# Generated by Django 4.0.4 on 2023-03-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasiKadir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
