# Generated by Django 4.0.4 on 2023-03-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oasiKadir', '0002_reservation_adults_reservation_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_clients',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
